mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/syt/user/mapper/xml/*.xml
server:
  port: 8203
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.190.101:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/guigu_syt_user?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    root: info
  file:
    path: user

feign:
  client:
    config:
      default:
        connect-timeout: 2000 #连接建立的超时时长，单位是ms，默认1s
        read-timeout: 2000 #处理请求的超时时间，单位是ms，默认为1s

  sentinel:
    enabled: true #开启Feign对Sentinel的支持

wx:
  open:
    app-id: wxc606fb748aedee7c # 微信开放平台 appid
    app-secret: 073e8e1117c1054b14586c8aa922bc9c #微信开放平台 appsecret
    redirect-uri: http://localhost:8200/api/user/wx/callback #微信开放平台 重定向url
    syt-base-url: http://localhost:3000 #预约挂号平台baserul