server:
  port: 8204
spring:
  rabbitmq:
    host: 192.168.190.101
    port: 5672
    username: guest
    password: guest
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.190.101:8848
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: info
  file:
    path: yun

#阿里云 OSS
aliyun:
  oss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    key-id:
    key-secret:
    bucket-name: kutake-syt
