server:
  port: 8201

mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/syt/hosp/mapper/xml/*.xml
spring:
  data:
    mongodb:
      database: syt
      host: 192.168.190.100
      password: '123456'
      port: 27017
      username: atguigu
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/guigu_syt_hosp?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    sentinel:
      transport:
        port: 8720
        dashboard: 127.0.0.1:8080
    nacos:
      discovery:
        server-addr: 192.168.190.101:8848
logging:
  level:
    root: info
    org:
      mongodb:
        driver:
          protocol:
            command: info
  file:
    path: hosp

feign:
  client:
    config:
      default:
        connect-timeout: 2000 #连接建立的超时时长，单位是ms，默认1s
        read-timeout: 2000 #处理请求的超时时间，单位是ms，默认为1s
  sentinel:
    enabled: true #开启Feign对Sentinel的支持